Object.assign(gameData, {
    "AUS": { name: "Australia", region: "oceania", capital: "Canberra", cities: { "Canberra": [149.12, -35.28], "Sydney": [151.20, -33.86], "Melbourne": [144.96, -37.81], "Perth": [115.86, -31.95], "Brisbane": [153.02, -27.46] }, facts: { "Canberra": "A planned capital designed by Walter Burley Griffin to resolve the rivalry between Sydney and Melbourne.", "Sydney": "Home to the iconic Opera House and Australia's oldest European settlement at Sydney Cove.", "Melbourne": "Consistently ranked as a top global city for liveability and Australia's cultural capital.", "Perth": "One of the most isolated major cities in the world, booming due to the mining industry.", "Brisbane": "A sub-tropical river city and the primary gateway to the Great Barrier Reef region." } },
    "FJI": { name: "Fiji", region: "oceania", capital: "Suva", cities: { "Suva": [178.44, -18.14] }, facts: { "Suva": "The largest city and a major economic and educational hub in the South Pacific." } },
    "KIR": { name: "Kiribati", region: "oceania", capital: "South Tarawa", cities: { "South Tarawa": [172.97, 1.32] }, facts: { "South Tarawa": "The center of a nation consisting of 33 coral atolls spanning all four hemispheres." } },
    "MHL": { name: "Marshall Islands", region: "oceania", capital: "Majuro", cities: { "Majuro": [171.38, 7.11] }, facts: { "Majuro": "A capital city built on a narrow atoll that consists of 64 distinct islands." } },
    "FSM": { name: "Micronesia", region: "oceania", capital: "Palikir", cities: { "Palikir": [158.16, 6.91] }, facts: { "Palikir": "The administrative center of a country comprised of over 600 volcanic islands and atolls." } },
    "NRU": { name: "Nauru", region: "oceania", capital: "Yaren", cities: { "Yaren": [166.92, -0.54] }, facts: { "Yaren": "The de facto capital of the world's smallest independent island nation." } },
    "NZL": { name: "New Zealand", region: "oceania", capital: "Wellington", cities: { "Wellington": [174.77, -41.28], "Auckland": [174.76, -36.84], "Christchurch": [172.63, -43.53] }, facts: { "Wellington": "The southernmost capital of a sovereign state and the 'windy' cultural heart of New Zealand.", "Auckland": "The largest Polynesian city in the world and New Zealand's primary economic engine.", "Christchurch": "Known as the 'Garden City' and the main logistics base for Antarctic exploration." } },
    "PLW": { name: "Palau", region: "oceania", capital: "Ngerulmud", cities: { "Koror": [134.47, 7.34] }, facts: { "Ngerulmud": "One of the least populous national capitals in the world, founded in 2006." } },
    "PNG": { name: "Papua New Guinea", region: "oceania", capital: "Port Moresby", cities: { "Port Moresby": [147.18, -9.44] }, facts: { "Port Moresby": "A strategic Pacific port and the hub for the nation's vast natural gas and gold wealth." } },
    "WSM": { name: "Samoa", region: "oceania", capital: "Apia", cities: { "Apia": [-171.76, -13.83] }, facts: { "Apia": "The historic center of Samoan culture and the final resting place of author Robert Louis Stevenson." } },
    "SLB": { name: "Solomon Islands", region: "oceania", capital: "Honiara", cities: { "Honiara": [159.95, -9.43] }, facts: { "Honiara": "Located on Guadalcanal, the site of a major turning-point battle in the Pacific during WWII." } },
    "TON": { name: "Tonga", region: "oceania", capital: "Nuku'alofa", cities: { "Nuku'alofa": [-175.20, -21.13] }, facts: { "Nuku'alofa": "The seat of the only remaining indigenous monarchy in the Pacific Islands." } },
    "TUV": { name: "Tuvalu", region: "oceania", capital: "Funafuti", cities: { "Funafuti": [179.19, -8.52] }, facts: { "Funafuti": "A highly vulnerable capital located on an atoll just meters above rising sea levels." } },
    "VUT": { name: "Vanuatu", region: "oceania", capital: "Port Vila", cities: { "Port Vila": [168.32, -17.73] }, facts: { "Port Vila": "A major Pacific financial center located in a region of intense volcanic activity." } }
});
