Object.assign(gameData, {
    "AUS": { name: "Australia", region: "oceania", capital: "Canberra", cities: { "Canberra": [149.12, -35.28], "Sydney": [151.20, -33.86], "Melbourne": [144.96, -37.81], "Perth": [115.86, -31.95], "Brisbane": [153.02, -27.46] }, facts: { "Canberra": "Chosen as the capital as a compromise between rivals Sydney and Melbourne.", "Sydney": "Home to the iconic Opera House and a global leader in finance and trade.", "Melbourne": "Consistently ranked as one of the world's most liveable cities.", "Perth": "A booming mining city and one of the world's most isolated metropolitan areas.", "Brisbane": "A major sub-tropical river city and gateway to the Great Barrier Reef." } },
    "FJI": { name: "Fiji", region: "oceania", capital: "Suva", cities: { "Suva": [178.44, -18.14] }, facts: { "Suva": "The largest city and a major economic hub in the South Pacific." } },
    "KIR": { name: "Kiribati", region: "oceania", capital: "South Tarawa", cities: { "South Tarawa": [172.97, 1.32] }, facts: { "South Tarawa": "The center of an island nation that spans all four hemispheres." } },
    "MHL": { name: "Marshall Islands", region: "oceania", capital: "Majuro", cities: { "Majuro": [171.38, 7.11] }, facts: { "Majuro": "A capital city built on an atoll consisting of 64 distinct islands." } },
    "FSM": { name: "Micronesia", region: "oceania", capital: "Palikir", cities: { "Palikir": [158.16, 6.91] }, facts: { "Palikir": "The capital of an archipelago of 600 islands in the Western Pacific." } },
    "NRU": { name: "Nauru", region: "oceania", capital: "Yaren", cities: { "Yaren": [166.92, -0.54] }, facts: { "Yaren": "The de facto capital of the world's smallest independent island nation." } },
    "NZL": { name: "New Zealand", region: "oceania", capital: "Wellington", cities: { "Wellington": [174.77, -41.28], "Auckland": [174.76, -36.84], "Christchurch": [172.63, -43.53] }, facts: { "Wellington": "The world's southernmost capital city of a sovereign state.", "Auckland": "Known as the 'City of Sails' and the largest Polynesian city in the world.", "Christchurch": "The largest city on the South Island and gateway to Antarctica." } },
    "PLW": { name: "Palau", region: "oceania", capital: "Ngerulmud", cities: { "Koror": [134.47, 7.34] }, facts: { "Ngerulmud": "One of the least populous national capitals in the world, founded in 2006." } },
    "PNG": { name: "Papua New Guinea", region: "oceania", capital: "Port Moresby", cities: { "Port Moresby": [147.18, -9.44] }, facts: { "Port Moresby": "Strategic Pacific port city and the hub of the nation's resource wealth." } },
    "WSM": { name: "Samoa", region: "oceania", capital: "Apia", cities: { "Apia": [-171.76, -13.83] }, facts: { "Apia": "The historic center of Samoan culture and a major regional seaport." } },
    "SLB": { name: "Solomon Islands", region: "oceania", capital: "Honiara", cities: { "Honiara": [159.95, -9.43] }, facts: { "Honiara": "Located on Guadalcanal, the site of a decisive turning-point battle in WWII." } },
    "TON": { name: "Tonga", region: "oceania", capital: "Nuku'alofa", cities: { "Nuku'alofa": [-175.20, -21.13] }, facts: { "Nuku'alofa": "The seat of the only remaining indigenous monarchy in the Pacific islands." } },
    "TUV": { name: "Tuvalu", region: "oceania", capital: "Funafuti", cities: { "Funafuti": [179.19, -8.52] }, facts: { "Funafuti": "The heart of one of the nations most vulnerable to rising sea levels." } },
    "VUT": { name: "Vanuatu", region: "oceania", capital: "Port Vila", cities: { "Port Vila": [168.32, -17.73] }, facts: { "Port Vila": "A strategic port city in a nation known for its intense volcanic activity." } }
});
