Object.assign(gameData, {
    "ARG": { name: "Argentina", region: "south_america", capital: "Buenos Aires", cities: { "Buenos Aires": [-58.38, -34.60], "Cordoba": [-64.18, -31.41] }, facts: { "Buenos Aires": "Known as the 'Paris of the South' for its European-influenced urban design." } },
    "BOL": { name: "Bolivia", region: "south_america", capital: "Sucre", cities: { "La Paz": [-68.11, -16.48], "Santa Cruz": [-63.18, -17.78] }, facts: { "La Paz": "The highest administrative capital in the world, located in the Andes mountains.", "Sucre": "The constitutional capital of Bolivia and a historic center of the silver trade." } },
    "BRA": { name: "Brazil", region: "south_america", capital: "Brasilia", cities: { "Sao Paulo": [-46.63, -23.55], "Rio de Janeiro": [-43.17, -22.90] }, facts: { "Brasilia": "A planned city in the interior designed to move development away from the coast." } },
    "CHL": { name: "Chile", region: "south_america", capital: "Santiago", cities: { "Santiago": [-70.66, -33.44], "Valparaiso": [-71.61, -33.04] }, facts: { "Santiago": "The financial heart of a nation that is the world's leading copper producer." } },
    "COL": { name: "Colombia", region: "south_america", capital: "Bogotá", cities: { "Bogotá": [-74.07, 4.71], "Medellín": [-75.56, 6.24] }, facts: { "Bogotá": "The fourth highest capital in South America and a center for higher education." } },
    "ECU": { name: "Ecuador", region: "south_america", capital: "Quito", cities: { "Quito": [-78.46, -0.18], "Guayaquil": [-79.88, -2.18] }, facts: { "Quito": "The capital closest to the Equator and a major historic Inca and Spanish hub." } },
    "GUY": { name: "Guyana", region: "south_america", capital: "Georgetown", cities: { "Georgetown": [-58.15, 6.80] }, facts: { "Georgetown": "Known as the 'Garden City of the West Indies,' located below sea level behind seawalls." } },
    "PRY": { name: "Paraguay", region: "south_america", capital: "Asunción", cities: { "Asunción": [-57.63, -25.26] }, facts: { "Asunción": "One of the oldest cities in South America, known as the 'Mother of Cities'." } },
    "PER": { name: "Peru", region: "south_america", capital: "Lima", cities: { "Lima": [-77.04, -12.04], "Cusco": [-71.96, -13.53] }, facts: { "Lima": "A massive coastal desert capital and a major center for global gastronomy.", "Cusco": "The former capital of the Inca Empire and the gateway to Machu Picchu." } },
    "SUR": { name: "Suriname", region: "south_america", capital: "Paramaribo", cities: { "Paramaribo": [-55.20, 5.85] }, facts: { "Paramaribo": "A multicultural city on the Suriname River with Dutch colonial architecture." } },
    "URY": { name: "Uruguay", region: "south_america", capital: "Montevideo", cities: { "Montevideo": [-56.16, -34.90] }, facts: { "Montevideo": "A major port city on the Rio de la Plata, known for its high quality of life." } },
    "VEN": { name: "Venezuela", region: "south_america", capital: "Caracas", cities: { "Caracas": [-66.90, 10.48], "Maracaibo": [-71.64, 10.64] }, facts: { "Caracas": "The political heart of a nation with the world's largest proven oil reserves." } }
});
